// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCG__8HbTsSjMeT6v6b1uFRys5F-yNsux4',
    appId: '1:589974754114:android:1253e54ef2be5295082edb',
    messagingSenderId: '589974754114',
    projectId: 'multimatch-flag-challenge',
    storageBucket: 'multimatch-flag-challenge.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJpMhgkSne5sqD2GyfvmbbUVxzTmTO1tE',
    appId: '1:589974754114:ios:bac877f9a506edfc082edb',
    messagingSenderId: '589974754114',
    projectId: 'multimatch-flag-challenge',
    storageBucket: 'multimatch-flag-challenge.firebasestorage.app',
    androidClientId: '589974754114-mto194m3b8r4o1g78ijvv79ksbce5mmi.apps.googleusercontent.com',
    iosClientId: '589974754114-klkgsaoudjuchj3qlfutqn4heotjpp8t.apps.googleusercontent.com',
    iosBundleId: 'com.worldflags.memory',
  );
}
